name: Publish @starktma/game-state-machine

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/game-state-machine/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          always-auth: true

      - name: Install
        run: npm install --workspace=packages/game-state-machine

      - name: Build
        run: npm run build --workspace=@starktma/game-state-machine

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          set -euo pipefail
          cd packages/game-state-machine
          name=$(node -p "require('./package.json').name")
          version=$(node -p "require('./package.json').version")
          if npm view "$name@$version" version >/dev/null 2>&1; then
            echo "$name@$version is already published on npm, skipping"
            exit 0
          fi
          echo "Publishing $name@$version"
          npm publish --access public
